### ISSUE TITLE
Introduce Ismail

### ISSUE THREAD

**Issue by HazemBittar** [katerynakim/isolate#12]
__As a site visitor, I want to learn more about Ismail__

> assigned to Hazem

### Repo

- [x] developed on a branch named `ismail-1`

### ismail.md

- [x] create the file
- [x] add their name as the main title
- [x] write a paragraph introduction
- [x] create a link back to the README

### README.md

- [ ] change their list item into a link

**Comment by ismailtugan** [comment]
you have to add my link in the README.md

**Comment by HazemBittar** [comment]
DONE
